MOTD:
  - ""
  - "&7               &3&lFluff &f&lEconomy"
  - ""
  - "&7                &6&lDISCORD &r/discord"
  - "&7                    &e&lSTORE &r/buy"
  - ""
Tips:
  - "Tip #1: Government Exchange is the slowest way to make money... Consider starting your own business!"
  - "Tip #2: Writing laws can give you an advantage."
  - "Tip #3: Invite others to produce more goods together."
  - "Tip #4: Spending 2 minutes to vote can yield $150 from the government each day."
  - "Tip #5: Inflation occurs! Make sure to keep investing and spending money!"
  - "Tip #6: House of Cards is a good show, maybe give it a watch!"
  - "Tip #7: Some Dream it, Some do it, some do both... be the one that does both!"
  - "Tip #8: You can get multiple sethomes using /homes + Lands."
  - "Tip #9: Buying a plot near spawn is a great way to invest in real-estate!"
  - "Tip #10: The Spawn was built by Craftinators."
  - "Tip #11: Don't overdo yourself on your first project! Keep it small and manageable!"
  - "Tip #12: Do /bal to see the true amount of money you have."
  - "Tip #13: Putting ideas into action is much better than leaving it as an idea!"
  - "Fact #1: Fluff Economy was originally going to be named HollowSeas: Economy after LoJoSho previous server."
  - "Fact #2: ToranStarline helped design the entire economy of Fluff Economy"
  - "Fact #3: Zombie_Striker is a pretty good person."
  - "Fact #4: The town of Winsford is actually a name from a previous server!"
  - "Fact #5: Zombie_Striker is a pretty cool person, may have overdone a contract by placing way to much stone."
  - "Fact #6: Stairs can be sit in!"
  - "Fact #7: BestatNothin_ & Onyxeagle274 are very interesting people!"